### ISSUE TITLE
Remove PK from seed files

### ISSUE THREAD

**Issue by thchia** [TechLadies/irrc-madwish#33]
In the seed files, we should not include the Primary Key in the seed data (e.g. `StudentID` etc.). Let the DB handle creating and inserting it.

**Comment by xuanjane** [comment]
Yes agree. 
The PK was inserted into the student seed data for testing purposes. Because the status update table's seed data will need to reference the student table's `StudentID`. So not fixing the PK for the 1 student seed data (test) would make it impossible to seed the other tables properly.

Is there a way to distinguish between seed data for testing purpose during development versus for the final product?

**Comment by thchia** [comment]
Yeah, we need to seed the tables with no references first, then query them when seeding the other tables. Not as straightforward, but I think this is the technically correct solution.

**Comment by xuanjane** [comment]
Cool... will study how to do this, any tips will be welcome!
Once done, would do up a PR.
